name: CI/CD pipeline for Spring Boot Docker App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java environment (for building the app)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the Spring Boot application
      - name: Build Spring Boot App
        run: mvn clean install -DskipTests=true

      # Step 5: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 6: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Build Docker Image
      - name: Build Docker image
        run: docker build -t vinay45/cicdspringboot:${{ github.sha }} .

      # Step 8: Push Docker Image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push vinay45/cicdspringboot:${{ github.sha }}

      # Step 9: Deploy to a running Docker container (Optional)
      - name: Deploy container (Optional)
        run: |
          docker stop springboot || true
          docker rm springboot || true
          docker run -d --name springboot -p 8080:8080 vinay45/cicdspringboot:${{ github.sha }}
